/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Chandu merovix (https://sketchfab.com/Shadowtiger)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vallam-wooden-boat-7357ab059f744223985423eb9cb01eb7
Title: Vallam (Wooden Boat)
*/
import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Boat(props) {
  const { nodes, materials } = useGLTF('/models/vallam_wooden_boat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        renderOrder = {1}
      />
    </group>
  )
}

useGLTF.preload('/models/vallam_wooden_boat.glb')
